apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotify-app
  template:
    metadata:
      labels:
        app: spotify-app
    spec:
      containers:
        - name: spotify-app
          image: michealken30/spotify-app:v1.1.0
          ports:
            - containerPort: 5000
