apiVersion: v1
kind: Service
metadata:
  name: spotify-app-service
spec:
  selector:
    app: spotify-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
  type: NodePort
